accounts/urls.py
from django.urls import path
from . import views

urlpatterns= [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),


    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),

    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),

]

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name="cart"),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>', views.remove_cart_item, name='remove_cart_item'),
    path('cart/update/<int:product_id>/<int:cart_item_id>', views.update_cart_quantity, name='update_cart_quantity'),
    path('checkout/', views.checkout, name='checkout'),

]

mengcraft/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('cat_entrance/', admin.site.urls),
    path('', views.home, name="home"),
    path('faq/', views.faq, name="faq"),
    path('impressum/', views.impressum, name="impressum"),
    path('data_policy/', views.data_policy, name="data_policy"),
    path('my-links/', views.links, name="links"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('contact/', include('contact.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.


class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError("You must have an email address")
        if not username:
            raise ValueError("You must have an username")
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,

        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):

    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(blank=True, max_length=100)
    house_number = models.CharField(blank=True, max_length=10)
    address_line_2 = models.CharField(blank=True, max_length=100)
    profile_picture = models.ImageField(blank=True, upload_to="userprofile")
    city = models.CharField(blank=True, max_length=20)
    zipcode = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

accounts/forms.py
from django import forms
from .models import Account, UserProfile
from django.forms import ValidationError

class RegistrationForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password'}),
        error_messages={'required': 'Bitte geben Sie ein Passwort ein.'}
    )

    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'}),
        error_messages={'required': 'Bitte bestätigen Sie Ihr Passwort.'}
    )

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'email', 'password']
        error_messages = {
            'first_name': {
                'required': 'Bitte geben Sie Ihren Vornamen ein.',
            },
            'last_name': {
                'required': 'Bitte geben Sie Ihren Nachnamen ein.',
            },
            'email': {
                'required': 'Bitte geben Sie eine E-Mail-Adresse ein.',
            },
        }

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs["placeholder"] = 'First Name'
        self.fields['last_name'].widget.attrs["placeholder"] = 'Last Name'
        self.fields['email'].widget.attrs["placeholder"] = 'Email'
        self.fields['password'].widget.attrs["placeholder"] = 'Enter Password'
        self.fields['confirm_password'].widget.attrs["placeholder"] = 'Repeat Password'
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Account.objects.filter(email=email).exists():  # Assuming Account model has an email field
            raise ValidationError(
                "Dieses E-Mail-Konto existiert bereits. Bitte verwenden Sie eine andere E-Mail-Adresse.")
        return email
    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise ValidationError('Die Passwörter stimmen nicht überein.')


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ("first_name", "last_name", "email")

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = 'form-control'


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages ={'invalid': "Image files Only"}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ("address_line_1", "house_number", "address_line_2", "city", "zipcode", "country", "profile_picture")

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = 'form-control'

templates/accounts/account_verification_email.html
{% autoescape off %}

    {% load static %}

    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Registrierung</title>
        </head>
        <body style="font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #f4f4f4;">
            <table align="center" width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; margin: 20px auto; padding: 20px; border: 1px solid #dddddd;">
                <!-- Banner Section -->
                <tr>
                    <td align="center">
                        <img src="{% static 'images/email_banner.png' %}" alt="Dank für deine Registrierung" style="max-width: 100%; height: auto;"/>
                    </td>
                </tr>

                <!-- Content Section -->
                <tr>
                    <td>
                        <p style="color: #333333;">Hallo {{user.first_name}},</p>
                        <p>Vielen Dank für deine Registrierung in meinem Shop! 🫶</p>
                        <p>Um die Registrierung freizuschalten, klicke bitte auf folgenden Link: <a href="https://{{domain}}{% url 'activate' uidb64=uid token=token %}" style="color: #1a73e8; text-decoration: underline;">https://{{domain}}{% url 'activate' uidb64=uid token=token %}</a> 😊</p>
                        <p>Wenn du deine Angaben nach der Freischaltung ändern möchtest, findest du alle möglichen Optionen unter „Mein Konto" in meinem <a href="https://www.mengcraft.de">Online Shop</a>.</p>
                        <p>Solltest du eine Frage haben, dann zögere bitte nicht mich zu kontaktieren.</p>
                        <p>Ich wünsche dir viel Spaß beim Shoppen!</p>
                        <p>Ganz liebe und blumige Grüße,</p>
                        <p>Meng von <a href="https://www.mengcraft.de">Mengcraft</a></p>
                    </td>
                </tr>
                <!-- Footer Section -->
                <tr>
                    <td align="center" style="padding-top: 20px;">
                        <p style="font-size: 12px; color: #888888;"></p>
                        <p style="font-size: 12px; color: #888888;"><a href="https://www.mengcraft.de/impressum/">Impressum:</a></p>
                        <p style="font-size: 12px; color: #888888;">© 2024 Mengcraft • Meng Ian Kuok • Wilmerdingstr. 14 • 38118 Braunschweig • Deutschland • E-Mail: mengian.kuok@gmail.com</p>
                    </td>
                </tr>
            </table>
        </body>
    </html>

{% endautoescape %}

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="padding-box">
    {% include 'includes/alerts.html' %}
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-6">
                <article class="card border shadow">
                    <header class="card-header">
                        <strong class="d-inline-block">Passwort ändern</strong>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form action="{% url 'change_password' %}" method="POST">
                                    {% csrf_token %}
                                     <div class="mb-3">
                                        <label for="current_password" class="form-label">Aktuelles Passwort</label>
                                        <div class="input-group">
                                            <input type="password" name="current_password" id="current_password" placeholder="Aktuelles Passwort" class="form-control" required>
                                            <span class="input-group-text">
                                                <i class="fa-solid fa-eye" id="toggleCurrentPassword" style="cursor: pointer;"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        <label for="new_password" class="form-label">Neues Passwort</label>
                                        <div class="input-group">
                                            <input type="password" name="new_password" id="new_password" placeholder="Neues Passwort" class="form-control" required>
                                            <span class="input-group-text">
                                                <i class="fa-solid fa-eye" id="toggleNewPassword" style="cursor: pointer;"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        <label for="confirm_password" class="form-label">Neues Passwort bestätigen</label>
                                        <div class="input-group">
                                            <input type="password" name="confirm_password" id="confirm_password" placeholder="Neues Passwort bestätigen" class="form-control" required>
                                            <span class="input-group-text">
                                                <i class="fa-solid fa-eye" id="toggleConfirmPassword" style="cursor: pointer;"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="text-end">
                                        <input type="submit" value="Senden" class="btn btn-custom-pink">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div> <!-- card-body .// -->
                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
    <script>
        const toggleCurrentPassword = document.querySelector('#toggleCurrentPassword');
        const currentPassword = document.querySelector('#current_password');

        const toggleNewPassword = document.querySelector('#toggleNewPassword');
        const newPassword = document.querySelector('#new_password');

        const toggleConfirmPassword = document.querySelector('#toggleConfirmPassword');
        const confirmPassword = document.querySelector('#confirm_password');

        toggleCurrentPassword.addEventListener('click', function () {
            // Toggle the type attribute for the current password field
            const type = currentPassword.getAttribute('type') === 'password' ? 'text' : 'password';
            currentPassword.setAttribute('type', type);

            // Toggle the eye icon for the current password field
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });

        toggleNewPassword.addEventListener('click', function () {
            // Toggle the type attribute for the new password field
            const type = newPassword.getAttribute('type') === 'password' ? 'text' : 'password';
            newPassword.setAttribute('type', type);

            // Toggle the eye icon for the new password field
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });

        toggleConfirmPassword.addEventListener('click', function () {
            // Toggle the type attribute for the confirm password field
            const type = confirmPassword.getAttribute('type') === 'password' ? 'text' : 'password';
            confirmPassword.setAttribute('type', type);

            // Toggle the eye icon for the confirm password field
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });
    </script>
{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->

<section class="padding-box">
    {% include 'includes/alerts.html' %}
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
                <article class="card shadow-sm mb-4 border">
                    <header class="card-header">
                        <strong class="d-inline-block">Angemeldet als: </strong>
                        <span>{{user.full_name}}</span>
                    </header>

                    <div class="card-body pb-0">
                        <div class="row">
                            <div class="col-md-6 mb-4">
                                <div class="card text-center shadow-sm h-100">
                                    <div class="card-body shadow">
                                        <h5 class="card-title">Anzahl Bestellungen</h5>
                                        <h4 class="display-3">{{orders_count}}</h4>
                                        <a href="{% url 'my_orders' %}" class="btn btn-custom-pink mt-3">Meine Bestellungen</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="card text-center shadow-sm h-100">
                                    <div class="card-body shadow">
                                        <img src="{{user_profile.profile_picture.url}}" alt="User Profile Picture" width="80" height="80" class="avatar mb-3 rounded-circle">
                                        <p class="mb-0">{{user.email}}</p>
                                        <a href="{% url 'edit_profile' %}" class="btn btn-custom-pink mt-3">Profil bearbeiten</a>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->
                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/delete_account.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="padding-box">
    {% include 'includes/alerts.html' %}
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-6">
                <article class="card border shadow">
                    <header class="card-header">
                        <strong class="d-inline-block">Profil löschen</strong>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form action="{% url 'delete_account' %}" method="POST">
                                    {% csrf_token %}

                                    <div class="text-end">
                                        <label for="delete_account" class="form-label">Bist du dir sicher, dass du dein Profil löschen möchtest? </label>

                                        <input type="submit"  id="delete_account" value="Profil löschen" class="btn btn-custom-pink">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div> <!-- card-body .// -->
                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="padding-box">
    {% include 'includes/alerts.html' %}
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
                <article class="card border shadow">
                    <header class="card-header">
                        <strong>Angemeldet mit: {{user.email}}</strong>
                    </header>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form action="{% url 'edit_profile' %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="row mb-3">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="first_name" class="form-label">Vorname</label>
                                                <input type="text" id='first_name' name="first_name" value="{{ user_form.first_name.value }}" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="last_name" class="form-label">Nachname</label>
                                                <input type="text" name="last_name" id="last_name" value="{{ user_form.last_name.value }}" class="form-control">
                                            </div>

                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="email" class="form-label">E-Mail</label>
                                                <input type="text" id="email" name="email" value="{{ user_form.email.value }}" class="form-control" style="background-color: #f0f0f0;" readonly>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mb-3">

                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-8">
                                            <div class="form-group">
                                                <label for="address_line_1" class="form-label">Straße</label>
                                                <input type="text" name="address_line_1" value="{{ profile_form.address_line_1.value }}" id="address_line_1" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-4">
                                            <div class="form-group">
                                                <label for="house_number" class="form-label">Nr.</label>
                                                <input type="text" name="house_number" value="{{ profile_form.house_number.value }}" id="house_number" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        <div class="form-group">
                                            <label for="address_line_2" class="form-label">Adresszusatz</label>
                                            <input type="text" id="address_line_2" name="address_line_2" value="{{ profile_form.address_line_2.value }}" class="form-control">
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="city" class="form-label">Stadt</label>
                                                <input type="text" id="city" name="city" value="{{ profile_form.city.value }}" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="zipcode" class="form-label">Postleitzahl</label>
                                                <input type="text" id="zipcode" name="zipcode" value="{{ profile_form.zipcode.value }}" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                 <label for="country" class="form-label">Land</label>
												<select id="country" name="country" class="form-control" readonly>
													<option value="Deutschland">Deutschland</option>
												</select>
                                            </div>
                                        </div>
                                    </div>
                                    <input type="submit" value="Speichern" class="btn btn-custom-pink">
                                </form>
                            </div>
                        </div>
                    </div> <!-- card-body .// -->
                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}


{% include 'includes/alerts.html' %}

<!-- ============================ REGISTER   ================================= -->
<section class="padding-box">
	<div class="card mx-auto" style="max-width: 600px; margin-top: 40px;">
	  <article class="box-wrapper">
		<header class="mb-4">
		  <h4 class="card-title text-center">Konto erstellen</h4>
		</header>
		<form action="{% url 'register' %}" method="POST">
			{% csrf_token %}
			<div class="row mb-3">
				<div class="col">
					<label for="first_name" class="form-label">Vorname</label>
					<input type="text" name="first_name" placeholder="Vorname" class="form-control" id="id_first_name">
				</div>
				<div class="col">
					<label for="last_name" class="form-label">Nachname</label>
					<input type="text" name="last_name" placeholder="Nachname" class="form-control" id="id_last_name">
				</div>
			</div>
			<div class="row mb-3">
				<div class="col-md-12">
					<label for="email" class="form-label">E-Mail</label>
					<input type="email" name="email" placeholder="E-Mail" class="form-control" id="id_email">
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 mb-3">
					<label for="password" class="form-label">Passwort</label>
					<div class="input-group">
						<input type="password" name="password" placeholder="Passwort" class="form-control" id="id_password">
						<span class="input-group-text">
							<i class="fa-solid fa-eye" id="togglePassword" style="cursor: pointer;"></i>
						</span>
					</div>
				</div>
				<div class="col-md-6 mb-3">
					<label for="confirm_password" class="form-label">Passwort bestätigen</label>
					<div class="input-group">
						<input type="password" name="confirm_password" placeholder="Passwort bestätigen" class="form-control" id="id_confirm_password">
						<span class="input-group-text">
							<i class="fa-solid fa-eye" id="toggleConfirmPassword" style="cursor: pointer;"></i>
						</span>
					</div>
				</div>
        </div>
			<br>
			<div class="d-grid">
				<button type="submit" class="btn btn-custom-pink">Registrieren</button>
			</div>
			{% if form.errors %}
				<ul>
					<br>
					{% for field in form %}
						{% for error in field.errors %}
							<li style="color: red;">{{ error }}</li>
						{% endfor %}
					{% endfor %}
				</ul>
			{% endif %}
			{% if form.non_field_errors %}
				<div style="color:red;">
					{{form.non_field_errors }}
				</div>
			{% endif %}

		</form>
	  </article>
	</div>
	<p class="text-center mt-4">Du hast bereits ein Konto? <a href="{% url 'login' %}" class="custom-link">Login</a></p>
</section>
<script>
        const togglePassword = document.querySelector('#togglePassword');
        const password = document.querySelector('#id_password');

        const toggleConfirmPassword = document.querySelector('#toggleConfirmPassword');
        const confirmPassword = document.querySelector('#id_confirm_password');

        togglePassword.addEventListener('click', function () {
            // Toggle the type attribute for the password field
            const type = password.getAttribute('type') === 'password' ? 'text' : 'password';
            password.setAttribute('type', type);

            // Toggle the eye icon for the password field
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });

        toggleConfirmPassword.addEventListener('click', function () {
            // Toggle the type attribute for the confirm password field
            const type = confirmPassword.getAttribute('type') === 'password' ? 'text' : 'password';
            confirmPassword.setAttribute('type', type);

            // Toggle the eye icon for the confirm password field
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });
    </script>
<!-- ========================= Register ========================= -->

{% endblock %}